// Conscript Animations
// By The One Epicplayer

$ModelName Humans/Conscript_Animations.mdl

$include "../humans/standardhierarchy.qci"
$include "../humans/standardikchains.qci"
$include "../humans/male/commonbones.qci"
$include "../humans/weaponmacros.qci"

$animblocksize 32

//$Attachment "anim_attachment_RH" "ValveBiped.Bip01_R_Hand" 0 0 0 rotate -90 -90 0 Already defined in commonbones.qci

$include "conscript_shared.qci"